version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing Python packages listed in requirements.txt"
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Running the deploy.sh script."
      - ./deploy.sh -e ${ENV}