AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  ENV:
    Description: Environment
    Type: String
    

Resources:
  TagProcessorDynamoDb:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub tag-processor-db-${ENV}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  
  TagNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Sub tag-notification-topic-${ENV}
  
  TagProcessorLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub tag-processor-${ENV} 
      CodeUri: ../tag-processor/build
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Timeout: 60
      Architectures:
        - x86_64
      Environment:
        Variables:
          TAG_PROCESSOR_DB: !Ref TagProcessorDynamoDb
          TAG_NOTIFICATION_TOPIC: !Ref TagNotificationTopic
  
  TagNotificationSenderLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub tag-notification-sender-${ENV} 
      CodeUri: ../tag-notification-sender/build
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Timeout: 60
      Architectures:
        - x86_64
       Events:
        TagNotificationSNSTopic:
          Type: SNS
          Properties:
            Topic: !Ref TagNotificationTopic

