name: Auto PR to Main on Merge to Dev

on:
    pull_request:
        branches:
            - dev
        types: [closed]

jobs:
    create-pull-request:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
        if: github.event.pull_request.merged == true
        steps:
            - name: Check out the latest code
              uses: actions/checkout@v3
              with:
                  ref: "dev"

            - name: Setup Git
              run: |
                  git config --global user.name "GitHub Actions"
                  git config --global user.email "actions@github.com"

            - name: Create a new branch
              run: |
                  PR_BRANCH="auto-pr-to-main-${GITHUB_RUN_ID}"
                  git checkout -b "$PR_BRANCH"
                  git push origin "$PR_BRANCH"

            - name: Create Pull Request to Main using GitHub CLI
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  gh auth setup-git
                  gh pr create --base main --head "$PR_BRANCH" --title "Merge dev into main" --body "Automatically created PR to merge changes from dev to main."
