name: Sanity Check

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  build:
    name: Run Sanity Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Navigate to web-scraper directory
      run: cd ./web-scraper

    - name: Install dependencies
      run: npm install

    - name: Run Sanity command
      run: npm run sanity
